name = "ACOPF_Extensions"
uuid = "f988bfc6-444a-4835-baec-c557783cd6e5"
authors = ["Mateo Llivisaca"]
version = "1.0.0-DEV"

[compat]
julia = "1.11.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]